### ISSUE TITLE
New releases and new packages

### ISSUE THREAD

**Issue by minusdavid** [indexdata/idzebra#16]
Hi folks!

I've noticed that there have been commits in 2019 and 2020, but the last release listed on the IndexData website (https://www.indexdata.com/resources/software/zebra/) are from 2018. The same goes for the Ubuntu and Debian Apt repository. 

Would it be possible to get some package updates? 

Cheers!

**Comment by dltj** [comment]
Thanks for writing, @minusdavid. I'm not sure when we can promise a new release, but I will look into it.

**Comment by minusdavid** [comment]
Thanks @dltj. 

I suppose that I'm less concerned with a new release being cut from the master branch than I am with there being no new packages.

Would IndexData be open to other people contributing packages? I see there's already a RPM specfile and debian/ directory, so creating new packages should be fairly trivial for new OS releases.

**Comment by adamdickmeiss** [comment]
There are no major changes since 2018. Only minor changes to packages.. So what platform(s) are missing?

**Comment by minusdavid** [comment]
> There are no major changes since 2018. Only minor changes to packages.. So what platform(s) are missing?

Looking at http://ftp.indexdata.dk/pub/zebra/debian/, Buster is missing. 

Looking at http://ftp.indexdata.dk/pub/zebra/ubuntu/, Focal is missing. 

I'm more concerned about Buster than Focal, since Focal has 2.1.4 available at https://packages.ubuntu.com/focal/idzebra-2.0, while Buster still only has 2.0.59 at https://packages.debian.org/buster/idzebra-2.0. 

Ubuntu Groovy is also coming out next month. (I doubt Debian Bullseye will be out for another year.)

**Comment by adamdickmeiss** [comment]
Zebra 2.2.0 released with packages for both Debian Buster and Ubuntu Focal.

**Comment by minusdavid** [comment]
Thanks, @adamdickmeiss. It's much appreciated!
