### ISSUE TITLE
Missing soname bump in zebra 2.2.1

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/idzebra#22]
When fixing #12, four instances/symbols were removed. This is a breaking ABI change and should have resulted in a soname/soversion bump in 2.2.1.

I missed this at the time.

https://github.com/indexdata/idzebra/blob/a63e96bdf9c5fe2296e5179c33e49b1bd9ee3538/configure.ac#L15

This should now be `ZEBRALIBS_VERSION_INFO=1:0:0`.

To maintain library compatibility, Debian bumps package sonames whenever symbols are removed from a library.

**Comment by dltj** [comment]
Logged in our internal tracker—thank you, @hughmcmaster.

**Comment by adamdickmeiss** [comment]
I'm inclined to just add those symbols again and use assert(0). This rule is a little rigid.

If this also means a change to the package name (not just version), then I'm very sure that's the best idea.

**Comment by hughmcmaster** [comment]
If the symbols/functions are reinstated as they were and assert(0) added, AIUI that won't be a breaking change and no soname bump is needed. We obviously don't need the problematic test.

In saying that, I can't find any implementations using the removed symbols.

With this course of action, I see no reason to bump the soname, although you should consider bumping the revision to 0:2:0.

**Comment by adamdickmeiss** [comment]
ok. Bumping that.

**Comment by adamdickmeiss** [comment]
https://github.com/indexdata/idzebra/pull/23

**Comment by hughmcmaster** [comment]
You'll also need to reinstate the four functions.

**Comment by adamdickmeiss** [comment]
done
