### ISSUE TITLE
ICU not handling exact phrase search correctly

### ISSUE THREAD

**Issue by minusdavid** [indexdata/idzebra#24]
It seems that Zebra, when in ICU mode, does not handle exact phrase search correctly. Here's a little example using a Koha-defined CCL search. 

It looks like some kind of tokenization issue... but I have no idea really.

ccl.properties:
ext 4=1 6=3
phr 4=1
Match-heading 1=Match-heading
do-not-truncate     5=100

bib1.attr
att 8804    Match-heading

**Comment by minusdavid** [comment]
![image](https://user-images.githubusercontent.com/6335343/101868568-bbce5f80-3bd1-11eb-8259-c2a4a5187391.png)

**Comment by minusdavid** [comment]
![image](https://user-images.githubusercontent.com/6335343/101868795-34cdb700-3bd2-11eb-88db-ea1490b565dc.png)

**Comment by minusdavid** [comment]
![image](https://user-images.githubusercontent.com/6335343/101868845-4c0ca480-3bd2-11eb-9be1-b32f9eecca27.png)

**Comment by dltj** [comment]
Thank you for the report.  I've logged the issue in Index Data's internal tracking system, and we will try to set aside some time to look at it.

**Comment by minusdavid** [comment]
Thanks @dltj. Much appreciated. I'm happy to provide any other information that may be needed.

**Comment by adamdickmeiss** [comment]
Cannot reproduce. You need to show exactly how you started yaz-client and the server log for your searches..

**Comment by minusdavid** [comment]
@adamdickmeiss : I can't post as text as Github won't render the XML it seems, but I could try to attach as content.

I can reproduce this across a range of Zebra versions, but there are so many variables... I'll try to provide what you've asked for.

**Comment by minusdavid** [comment]
The full process for what I'm doing is using Docker containers provided by https://gitlab.com/koha-community/koha-testing-docker

Re-configure Zebra for ICU vs CHR:

-  `vi /etc/koha/zebradb/etc/default.idx`
- Change "charmap word-phrase-utf.chr" to "icuchain words-icu.xml" for index w
- Change "charmap word-phrase-utf.chr" to "icuchain phrases-icu.xml" for index p
- Re-index records in Zebra using `koha-rebuild-zebra -f -b -v kohadev`
 
Searching:
- `vi /etc/koha/sites/kohadev/koha-conf.xml`
- I obtain "unix:/var/run/koha/kohadev/authoritysocket" from the configuration
- `yaz-client unix:/var/run/koha/kohadev/authoritysocket`
- `base authorities`
- `querytype ccl2rpn`
- `set_cclfile /etc/koha/zebradb/ccl.properties`
- `format xml`
- `elements zebra::snippet`
- `f Any,ext=e`

This shows the following:
`
Sent presentRequest (1+1).
Records: 1
Record type: XML
<record xmlns="http://www.indexdata.com/zebra/">
  <snippet name="Any" type="p">Gontarski S <s>E</s></snippet>
</record>nextResultSetPosition = 2
Elapsed: 0.004530
`

I'll attach a more complete Zebra server log, but the RPN request it creates is: @attrset Bib-1 @attr 1=1016 @attr 4=1 @attr 6=3 e

**Comment by minusdavid** [comment]
[zebra_files.zip](https://github.com/indexdata/idzebra/files/5693626/zebra_files.zip)

**Comment by minusdavid** [comment]
When I switch back to CHR indexing, Zebra works as expected (done by changing back to .chr files in /etc/koha/zebradb/etc/default.idx and restarting Zebra and reindexing records in Zebra).

That shows the following:
`Z> f Any,ext=e`

`Sent searchRequest.
Received SearchResponse.
Search was a success.
Number of hits: 0, setno 1
SearchResult-1: term=e cnt=0
records returned: 0
Elapsed: 0.004760`

**Comment by minusdavid** [comment]
[zebra_chr.zip](https://github.com/indexdata/idzebra/files/5693644/zebra_chr.zip)

**Comment by minusdavid** [comment]
Ah, that CHR isn't right as I didn't re-index the right database...

**Comment by minusdavid** [comment]
That should have been `koha-rebuild-zebra -f -a -v kohadev`

**Comment by minusdavid** [comment]
CHR:
f Any=e (21 results)
f Any,ext=e (0 results)

ICU:
f Any=e (21 results)
f Any,ext=e (5 results)

Snippets for those 5:
- `<snippet name="Any" type="p">Gontarski S <s>E</s></snippet>`
- `<snippet name="Any" type="p">Malmstad John <s>E</s></snippet>`
- `<snippet name="Any" type="p">Moo Barbara <s>E</s></snippet>`
- `<snippet name="Any" type="p">Gao <s>E</s></snippet>`
- `<snippet name="Any" type="p">Johns W <s>E</s></snippet>`

This is clearly a bug.

According to https://software.indexdata.com/zebra/doc/querymodel-zebra.html, @attr 4=1 structure attr with completeness attr of @attr 6=3 should be using the 'p' register which should be normalized and not tokenized. But it is clearly tokenized.

Note that these particular logs are for an old Zebra 2.0.59, but I have reproduced it on Zebra 2.1+.

`f Any,ext="S E"`
`<snippet name="Any" type="p">cat OSt0 Silk M <s>S </s>Michael Stephen 1941 Aristophanes </snippet>`
`<snippet name="Any" type="p">Gontarski <s>S </s>E</snippet>`

It's the end of the work day so I have to leave, but I can try this again using the latest Zebra, and I'm quite confident that I'll get the same result.

**Comment by adamdickmeiss** [comment]
Your `phrases-icu.xml` indeed tokenizes which gives the wrong behavior. Use the yaz-utility `yaz-icu` to verify your mappings. Currently your file behaves like this for input `a b c`.

    $ echo a b c|~/proj/yaz/util/yaz-icu -c phrases-icu.xml
    1 1 'a ' 'a '
    2 1 'b ' 'b '
    3 1 'c
    ' 'c
    '

That's 3 tokens.. It should be one (say one title).

The problem is the tokenize line.. Change it to:

     <tokenize rule="s"/>

Now we get:

    $ echo a b c|~/proj/yaz/util/yaz-icu -c phrases-icu.xml
    1 1 'a b c
    ' 'a b c
    '
(it could be prettier with control characters in the output).

The `phrases-icu.xml` that comes with Zebra gives:

    $ echo a b c|~/proj/yaz/util/yaz-icu -c phrases-icu.xml
    1 1 'a b c' 'a b c'

**Comment by minusdavid** [comment]
Hmm, I've updated the tokenize rule as you've advised, but I'm still getting strange results.

Unfortunately, zebra::index doesn't seem to work with ICU. That is, it doesn't show the contents of indexes, while the contents do appear with CHR.

When I run this search:
f Match-heading,phr,ext,do-not-truncate="e"

I get a hit with this snippet: `<snippet name="Match-heading" type="p" fields="Match">Gontarski S <s>E</s></snippet>`

However, this search yields 0 search results:
f Match-heading,phr,ext,do-not-truncate="Gontarski S E"

Interestingly... this is the exact same behaviour when I use the phrases-icu.xml that comes with Zebra (/usr/share/idzebra-2.0/tab/phrases-icu.xml)

**Comment by minusdavid** [comment]
I imagine that we probably used that tokenize rule, because using the "s" sentence tokenization doesn't seem to work...

**Comment by minusdavid** [comment]
Ok maybe this is related to the bugs in 2.0.59 now as the following search is "working":
 f Match-heading,phr,ext,do-not-truncate="Gontarski S. E"

Searchresult: `SearchResult-1: term=Gontarski S  cnt=1`
Snippet: `<snippet name="Match-heading" type="p" fields="Match"><s>Gontarski S </s>E</snippet>`

I'll try with a newer version of Zebra...

**Comment by minusdavid** [comment]
Hmm nope I've installed the latest Zebra and I'm still getting the same problem using /usr/share/idzebra-2.0/tab/phrases-icu.xml and Koha's phrases-icu.xml...

This is what Koha sent to Zebra for indexing:

<z:index name="Match:w Match:p Match-heading:p Match-heading:s">Gontarski, S. E</z:index>

**Comment by minusdavid** [comment]
With both phrases-icu.xml files I am noticing 2 indexes for Match-heading. 

Aha... I wish zebra::index worked, but it appears likely that the first contains "gontarski s " and the second contains "e".

This is proven by running these 2 searches to procure the same record:

f Match-heading,ext="Gontarski S "
f Match-heading,ext="E"

This is at odds with what yaz-icu is saying...
` echo 'Gontarski S E' | yaz-icu -c /etc/koha/zebradb/etc/phrases-icu.xml`
`1 1 'gontarski s e' 'Gontarski S E'`

**Comment by minusdavid** [comment]
Any insight into what might be happening here?

**Comment by adamdickmeiss** [comment]
There were fixes in Zebra 2.0.60 for exactly phrase searching.. And you have tried that. And reindexed of course.. :-) Here's what you need to do to make it somewhat easy for me to see what goes.

Provide:  
 *  the record you are referring to (which I don't have) 
 * A zebra cfg that is fully working ..
 * Files that zebra.cfg is referring to.. Including XSL or other that is used for indexing.
 * The search and what YOU get .. And what YOU expected to get

Yes.. I already have some of the files .. perhaps you changed them since then? .. No referral to /etc or otherwise which I don't have.

I don't care about the CHR case.. Just provide the case that is failing where you think it should be different.

We'll sort this out. Thx

**Comment by minusdavid** [comment]
I've been working with Zebra in the Koha context, but I'll move to just working with Zebra on its own and hopefully that way I'll be able to make it easier for you to reproduce.

**Comment by minusdavid** [comment]
Setup (without Dockerfile):
apt-get install idzebra-2.0 yaz
Extract idzebra.tar.gz to /etc/idzebra/.

Terminal 1:
mkdir -p /var/lib/zebra/authorities/{register,shadow,tmp,key}
zebraidx -c /etc/idzebra/zebra-authorities-dom.cfg -g marcxml -d authorities init
zebraidx -c /etc/idzebra/zebra-authorities-dom.cfg -g marcxml -d authorities commit
zebraidx -c /etc/idzebra/zebra-authorities-dom.cfg -g marcxml -d authorities update /etc/idzebra/records
zebraidx -c /etc/idzebra/zebra-authorities-dom.cfg -g marcxml -d authorities commit
zebrasrv -f /etc/idzebra/vhost.cfg

Terminal 2:
yaz-client unix:/var/run/authoritysocket 

querytype ccl2rpn
set_cclfile /etc/idzebra/ccl.properties
format xml
elements zebra::snippet
base authorities
f Match-heading,ext="Gontarski S E"

I *expect* 1 result, but I *get* 0 results.

f Match-heading,ext="e"

I *expect* 0 results, but I *get* 1 result.
Snippet: `<snippet name="Match-heading" type="p" fields="Match">Gontarski S <s>E</s></snippet>`

f Match-heading,ext="Gontarski S "

I *expect* 0 results, but I *get* 1 result.
Snippet: `<snippet name="Match-heading" type="p" fields="Match"><s>Gontarski S </s>E</snippet>`

**Comment by minusdavid** [comment]
[test_files.zip](https://github.com/indexdata/idzebra/files/5722456/test_files.zip)

**Comment by minusdavid** [comment]
(Side note: if you use `elements zebra::index` you'll notice that you're not able to see any of the indexed data. `elements index` should show you what was indexed via `authority-zebra-indexdefs.xsl`. For example, in the latter case: `<z:index name="Match:w Match:p Match-heading:p Match-heading:s">Gontarski, S. E</z:index>`

**Comment by adamdickmeiss** [comment]
The original record has punctuation.. That makes it split in a "funny" way and fully explains the odd results

    $ ~/proj/yaz/util/yaz-icu -c phrases-icu.xml 
    Gontarski, S. E.
    1 1 'gontarski s ' 'Gontarski S '
    2 1 'e' 'E'

We'll how we can fix that.

**Comment by minusdavid** [comment]
Ah, it's not all punctuation, but rather punctuation for ending a sentence. This makes sense since we're using "sentence" tokenization in this case. 

And in Koha we're using "line" tokenization which is even worse:
```
echo "Gontarski, S. E." | yaz-icu -c /etc/koha/zebradb/etc/phrases-icu.xml
1 1 'gontarski ' 'Gontarski '
2 1 's ' 'S '
3 1 'e
' 'E
'
```

If I remove the tokenize element from phrases-icu.xml, I get the following:
```
echo "Gontarski, S. E." | yaz-icu -c /etc/koha/zebradb/etc/phrases-icu.xml
1 1 'gontarski s e
' 'Gontarski S E
'
```

I know you said that you didn't want to hear about CHR but CHR doesn't tokenize the content in the "p" register.

Also, if we look at https://software.indexdata.com/zebra/doc/querymodel-zebra.html#querymodel-pqf-apt-mapping-structuretype it does say that the "p" register is "Character normalized, but not tokenized index for phrase matches".

So... I think that the solution might be to just remove the "tokenize" element from phrases-icu.xml.

**Comment by minusdavid** [comment]
I'm keen to hear what you think, Adam. If you agree, I'll remove the token element from phrases-icu.xml and that would probably be case closed.

**Comment by minusdavid** [comment]
Well, I could do a pull request to remove it from https://github.com/indexdata/idzebra/blob/master/tab/phrases-icu.xml if you agree.

I wouldn't mind having a commit in idzebra heh.

**Comment by minusdavid** [comment]
I've tried my idea using test_files.zip and removing the tokenize line from phrases-icu.xml and it worked as expected. 

Still going to wait to hear from @adamdickmeiss before I proceed but I'm feeling optimistic.

**Comment by adamdickmeiss** [comment]
I think we should make a separate file, called something like complete-icu.xml. with the tokenize element removed (what you end up using). ICU really does try to split it into "phrases".. I'm afraid a change in a file like that could lead to surprises to systems that rely on a breakup into "phrases". So make PR with that new file, thx

**Comment by minusdavid** [comment]
I can see where you're coming from, since changing behaviour in upgrades can be surprising/problematic, but you might want to add more notes to your documentation in that case. 

As I noted above, https://software.indexdata.com/zebra/doc/querymodel-zebra.html#querymodel-pqf-apt-mapping-structuretype says that the "p" register is "Character normalized, but not tokenized index for phrase matches".

You may want to add a note saying that is not true when using the default phrases-icu.xml?

**Comment by adamdickmeiss** [comment]
I'm going to reopen this, as I think this should be considered a bug. Will just change phrases-icu.xml ..
