### ISSUE TITLE
Datetime format in Zebra logs is incomplete and difficult to parse

### ISSUE THREAD

**Issue by minusdavid** [indexdata/idzebra#25]
At the moment, Zebra logs lines in the format hh:mm:ss-DD/MM (e.g. 09:47:33-17/12). 

This format omits the year, doesn't sort easily, is difficult to read programmatically, and is generally atypical for datetime.

I propose using ISO 8601 instead (e.g. "2020-12-17 09:47:33" or "2020-12-17T09:47:33", since it contains the complete datetime information, it sorts easily, and is easily read by both humans and machines.

**Comment by MikeTaylor** [comment]
+1

**Comment by adamdickmeiss** [comment]
We are not going to change the default format. That would be a breaking change. You can control the format with YAZ function `yaz_log_time_format` and for YAZ GFS (which zebrasrv) is based on - with option -m. For example
 
    zebrasrv -m "%F %T"

**Comment by minusdavid** [comment]
Sounds good to me. 

Using "man zebrasrv", I'd looked for an option using like this before opening the issue, but didn't find one.

However, looking again, I se that it says "The options for zebrasrv are the same as those for YAZ' yaz-ztest."

When I do "man yaz-ztest", I do see the "-m time-format" option. 

It might be worth synchronizing those man pages more.
