### ISSUE TITLE
Temporary result sets not being cleaned up

### ISSUE THREAD

**Issue by minusdavid** [indexdata/idzebra#33]
I'm running Zebra 2.2.3 and I've noticed for the past few months that the temporary result sets aren't being cleaned up. While the file size varies, it's not uncommon to get results sets that are over 1GB in size (e.g. 2.7G Jan 18 15:55 zrs_11775_R0m3x0), and eventually these lead to a volume full. 

As a workaround, I can implement a cronjob to delete results sets over a certain age, but it would be good if Zebra was cleaning up after itself. 

(I've noticed the same problem on Zebra 2.0.60 although to a lesser degree. It might just be because that instance isn't receiving queries with as large of results.)

**Comment by minusdavid** [comment]
An old list entry helped me to figure out what was going on a bit: http://lists.indexdata.dk/pipermail/zebralist/2004-February/000388.html

In the NEWS, it mentions these files:
Bug #781: Easier tracking of result sets. We only do this when mkstemp
is available (most moderun Unixes supports this). The PID is included
in filename : tempdir/zrs_PID_XXXXXX.

I can see in rset/rstemp.c that the file template is made up of zrs_PID_ as well... but I don't know the Zebra internals enough to know where this file should be cleaned up

**Comment by minusdavid** [comment]
I've looked at this one some more and when I send searches I am seeing that it usually cleans up searches immediately... and sometimes it takes nearly a minute longer. 

Not sure what is happening in the cases where the files aren't getting cleaned up... 

I'm also curious about the large file sizes. I'm sending searches that seem to fetch all the records, but they're only maybe 131MB in size (the register file is about 5GB).

**Comment by minusdavid** [comment]
What data is stored in these zrs_PID_* files? Is it just search results or does it include the search query? I'm curious if someone has managed to inflate the size of these files using carefully crafted queries...

**Comment by minusdavid** [comment]
I've installed the "dbview" utility to view these result sets.

For a result set that had 3325 hits, it says that there are 22038 records in it...

dbview -i zrs_164279_yuZM3d
File version  : 3
Last update   : 00/00/1900
Number of recs: 22038
Header length : 2
Record length : 0

**Comment by adamdickmeiss** [comment]
> I've installed the "dbview" utility to view these result sets.
> 
> For a result set that had 3325 hits, it says that there are 22038 records in it...
> 
> -rw------- 1 root root 1.3G May 24 13:43 zrs_164279_yuZM3d
> 
> dbview -i zrs_164279_yuZM3d File version : 3 Last update : 00/00/1900 Number of recs: 22038 Header length : 2 Record length : 0

dbview vies dbase III files. Zebra is not using that format for its temporary files.

As for truncation, temporary files, Zebra may generate them in truncation, snippet handling and local ID search. As for the first case (truncation), it takes quite some effort to make it generate temporary files. Please supply your main zebra.cfg that you use, so we can see what settings you have in there.

**Comment by adamdickmeiss** [comment]
Temporary result set files are removed as soon as the result-set is "deleted" in the Z39.50. They are also removed when a session is terminated.

They are *not* removed, if zebrasrv process is terminated with a signal such as SIGTERM, SIGABRT .. This could be a bug that you have encountered and the symptom is result sets left behind.

**Comment by minusdavid** [comment]
I don't think these zebrasrv processes would've been terminated by a signal but perhaps a crash?

Just now I found the following left over on a test server
-rw------- 1 root root 1.3G May 24 13:04 zrs_162047_0sZRCr
-rw------- 1 root root 1.3G May 24 13:03 zrs_162053_oINPSR
-rw------- 1 root root 1.3G May 24 14:44 zrs_170683_BPAIdq
-rw------- 1 root root 1.3G May 24 14:53 zrs_170683_CYGahq
-rw------- 1 root root 1.3G May 24 14:54 zrs_170683_S19vct
-rw------- 1 root root 1.3G May 24 15:34 zrs_173751_CYaWUo

This is the same 1,000,000+ record Zebra database that has the problems mentioned in https://github.com/indexdata/idzebra/issues/35

**Comment by minusdavid** [comment]
I'll email you the zebra.cfg. Thanks for looking!

**Comment by adamdickmeiss** [comment]
Please try this branch and see if that solves your problem: https://github.com/indexdata/idzebra/tree/zebra-close-on-sigterm

What options do you pass when invoking zebrasrv ?

**Comment by adamdickmeiss** [comment]
Fixed in #38

**Comment by minusdavid** [comment]
Thanks for looking into this one and doing that merge!

Sorry for not getting to that branch. Since the problem only happens sometimes, it's a difficult one to test.
