### ISSUE TITLE
memMax has undocumented 2,147,483,647 byte limit

### ISSUE THREAD

**Issue by minusdavid** [indexdata/idzebra#34]
I tried turning up memMax to 4096M as I have a large record set to index and it threw this error:

malloc_consolidate(): invalid chunk size

So I reduced memMax to 2048M and that led to this error:

zebraidx(118435) [fatal] key_block.c:200: Out of memory - malloc(-1073741824 bytes)
zebraidx: xmalloc.c:253: xmalloc_fatal: Assertion `size < MALLOC_SIZE_MAX' failed.

That negative number made me think that the value from memMax  must be a signed 32 bit integer.

Looking at https://github.com/indexdata/idzebra/blob/master/index/key_block.c#L200, I noticed that indeed the "mem" variable has an "int" data type. 

I don't know if you have to support 32 bit OSes still, so I don't know what the solution is. However, since it's memory, I think you'd be safe to use an unsigned integer at a minimum. That wouldn't quite get us to support for 4GB for memMax, but almost.

In any case, https://software.indexdata.com/zebra/doc/zebra-cfg.html says memMax "Specifies size of internal memory to use for the zebraidx program. The amount is given in megabytes - default is 4 (4 MB). The more memory, the faster large updates happen, up to about half the free memory available on the computer."

It would probably be a good idea to revise that to say that the maximum is currently 2047MB.

(Also, it would be good to have a sanity check on that memory allocation to make sure it's a positive integer at the very least.)

**Comment by adamdickmeiss** [comment]
Thx for reporting, we've changed the size to be handled as size_t. Funny that the old default was 4 (in fact 8) MB which seems so low these days :-)

**Comment by minusdavid** [comment]
Thanks for the rapid response, Adam! 

Haha. Just a bit low these days!

When might there be another Zebra release?
