### ISSUE TITLE
Possible API breakage in idzebra 2.2.7

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/idzebra#54]
When preparing v2.2.7 for Debian, the build system warned that one public symbol had been removed. That was `getFnameTmp`.

I also found a signature change in `extract_get_fname_tmp`, which now takes the string length.

While these are technically API breakages and the library soname should be bumped, do you know of any programs linking against these symbols? Debian doesn't have any software linking against libidzebra-2.0-0.

I'm just wondering whether you believe it necessary to bump the soname version.

**Comment by hughmcmaster** [comment]
Any thoughts on this, @adamdickmeiss?

**Comment by adamdickmeiss** [comment]
I don't know of any programs/libraries using these symbols.

I'd hate bumping the SO-name. 

If you insist, I'd rather make it compatible again (keep getFnameTmp and make extract_get_fname_tmp unmodified).

FWIW, the Zebra 2.2.7 is an important release fixing various possible overflows.

**Comment by hughmcmaster** [comment]
Thanks for confirming. I've spoken with some other Debian Developers about this situation, and they've all said it's okay to drop `getFnameTmp` and tighten the linker version against `extract_get_fname_tmp`, since there is no known program or library using those symbols.

One developer also pointed out that both symbols end in `Tmp`/`tmp` and asked whether they're actually supposed to be internal and not exported.

**Comment by hughmcmaster** [comment]
> FWIW, the Zebra 2.2.7 is an important release fixing various possible overflows.

Yes, I want 2.2.7 in Debian unstable and testing before the full code freeze.

**Comment by adamdickmeiss** [comment]
There are many public symbols in Zebra that aren't really public. They are "package private"  - a concept that doesn't except in C.  static modifier are object file private and is not good for symbols shared between object files.

In particular these symbols are not declared in any public headers. For zebra, public headers are in include/idzebra (part of dev package), whereas internal symbols are declared anywhere and NOT part of dev package (source only used in compilation). THe removed symbols were part of index/index.h .. All symbols in there are package private.
